In [1]:
pip install tensorflow

Note: you may need to restart the kernel to use updated packages.


### importing the libraries

In [7]:
import tensorflow as tf
import numpy as np
import pandas as pd

In [8]:
tf.__version__

'2.9.1'

In [10]:
data=pd.read_csv("C:/Users/91790/Downloads/Galgotias-University-main/Galgotias-University-main/Churn_Modelling.csv")
data.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [11]:
x=data.iloc[:,3:-1].values
y=data.iloc[:,-1].values

In [12]:
print(x)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [14]:
print(y)

[1 0 1 ... 1 1 0]


### Data Description 

In [15]:
data.describe()

RowNumber    CustomerId   CreditScore           Age        Tenure  \
count  10000.00000  1.000000e+04  10000.000000  10000.000000  10000.000000   
mean    5000.50000  1.569094e+07    650.528800     38.921800      5.012800   
std     2886.89568  7.193619e+04     96.653299     10.487806      2.892174   
min        1.00000  1.556570e+07    350.000000     18.000000      0.000000   
25%     2500.75000  1.562853e+07    584.000000     32.000000      3.000000   
50%     5000.50000  1.569074e+07    652.000000     37.000000      5.000000   
75%     7500.25000  1.575323e+07    718.000000     44.000000      7.000000   
max    10000.00000  1.581569e+07    850.000000     92.000000     10.000000   

             Balance  NumOfProducts    HasCrCard  IsActiveMember  \
count   10000.000000   10000.000000  10000.00000    10000.000000   
mean    76485.889288       1.530200      0.70550        0.515100   
std     62397.405202       0.581654      0.45584        0.499797   
min         0.000000       1.000000      0.00000        0.000000   
25%         0.000000       1.000000      0.00000        0.000000   
50%     97198.540000       1.000000      1.00000        1.000000   
75%    127644.240000       2.000000      1.00000        1.000000   
max    250898.090000       4.000000      1.00000        1.000000   

       EstimatedSalary        Exited  
count     10000.000000  10000.000000  
mean     100090.239881      0.203700  
std       57510.492818      0.402769  
min          11.580000      0.000000  
25%       51002.110000      0.000000  
50%      100193.915000      0.000000  
75%      149388.247500      0.000000  
max      199992.480000      1.000000

# Encoding  the data

In [18]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
x[:,2]= le.fit_transform(x[:,2])

In [19]:
print(x)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [25]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1])],remainder='passthrough')
x=np.array(ct.fit_transform(x))

In [26]:
print(x)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


### Splitting the data into training and testing

In [27]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

# Standardizing the data

In [29]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

### Intialising ANN

In [30]:
ann=tf.keras.models.Sequential()

### Adding the input layer and the hidden layer

In [32]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

### Adding the second hidden layer

In [33]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

### Adding the output layer

In [35]:
ann.add(tf.keras.layers.Dense(units=1,activation='sigmoid'))

### Compiling the ANN

In [38]:
ann.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

### Training the ANN on training set

In [41]:
ann.fit(x_train,y_train,batch_size=32,epochs=50)

Epoch 1/50
250/250 [==============================] - 1s 3ms/step - loss: 0.4612 - accuracy: 0.8009
Epoch 2/50
250/250 [==============================] - 1s 3ms/step - loss: 0.4456 - accuracy: 0.8044
Epoch 3/50
250/250 [==============================] - 1s 3ms/step - loss: 0.4384 - accuracy: 0.8059
Epoch 4/50
250/250 [==============================] - 1s 3ms/step - loss: 0.4329 - accuracy: 0.8074
Epoch 5/50
250/250 [==============================] - 1s 3ms/step - loss: 0.4277 - accuracy: 0.8111
Epoch 6/50
250/250 [==============================] - 1s 3ms/step - loss: 0.4228 - accuracy: 0.8101
Epoch 7/50
250/250 [==============================] - 1s 3ms/step - loss: 0.4180 - accuracy: 0.8151
Epoch 8/50
250/250 [==============================] - 1s 3ms/step - loss: 0.4140 - accuracy: 0.8195
Epoch 9/50
250/250 [==============================] - 1s 3ms/step - loss: 0.4105 - accuracy: 0.8227
Epoch 10/50
250/250 [==============================] - 1s 3ms/step - loss: 0.4072 - accuracy: 0.8248

### Predicting the test results

In [42]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

1/1 [==============================] - 0s 289ms/step
[[False]]


In [44]:
y_pred = ann.predict(x_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

63/63 [==============================] - 0s 2ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### Confusion matrix

In [45]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1506   89]
 [ 190  215]]


0.8605